source 'https://rubygems.org'

ruby '2.2.5'

gem 'rails', '4.2.1'
gem 'pg'
gem 'mongoid'

gem 'haml'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem "font-awesome-rails"
gem 'owlcarousel-rails'

gem 'rails-i18n'

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-ui-rails'

gem 'sdoc', '~> 0.4.0', group: :doc

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'thin'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rspec-rails'

  gem 'erb2haml'

  gem 'web-console', '~> 2.0'
  gem 'spring'

  gem "better_errors"
  gem "binding_of_caller"
  gem 'factory_girl_rails'
  gem 'faker'
end

gem 'carrierwave'
gem 'mini_magick'
gem 'ckeditor'
gem 'wkhtmltopdf-binary-edge', '~> 0.12.3.0'
gem 'wicked_pdf'
# gem 'pdfkit'


#gem 'gibbon', git: 'git://github.com/amro/gibbon.git'
gem 'settingslogic'

gem 'devise'
gem 'omniauth', '~> 1.2.2'
gem 'oauth2', '~> 1.0.0'
gem 'omniauth-oauth2', '~> 1.3.0'
gem 'omniauth-facebook', '~> 2.0.1'
gem 'omniauth-google-oauth2', '~> 0.2.6'
gem 'omniauth-linkedin-oauth2', '~> 0.1.5'

gem 'nested_form_fields'

gem 'httparty'

gem 'yaml_db'

gem 'gibbon'
